language: go

go:
  - 1.9.x
  - 1.10.x

before_install:
  - sudo apt-get install ragel
  - go get -v gopkg.in/alecthomas/gometalinter.v2
  - go get golang.org/x/tools/cmd/goyacc

script:
  - make
  - make linter
  - make test
